name: Build Package # https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Manual Run

jobs:
  build:
    name: Swift on ${{ matrix.os }} # Swift ${{ matrix.swift }} on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        swift: ["5.7.1"]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: swift-actions/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift }}
      - name: Get swift version
        run: swift --version

      - uses: actions/checkout@v2
      - name: Build
        run: swift build
      - name: Run tests
        run: swift test